// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3WBComQUeCYBBYp6qPYrvIkLiZKuHtsU',
    appId: '1:70223472961:web:b78c8b38538cbfc8d419c0',
    messagingSenderId: '70223472961',
    projectId: 'fir-task-490d9',
    authDomain: 'fir-task-490d9.firebaseapp.com',
    storageBucket: 'fir-task-490d9.appspot.com',
    measurementId: 'G-Y2C77MJ9L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD72N6k0YoSQhk67McNlVUMCrVcC7IEdWo',
    appId: '1:385809129495:android:f12ecb6aba0c719c45bc52',
    messagingSenderId: '385809129495',
    projectId: 'appquanly-57c64',
    storageBucket: 'appquanly-57c64.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3WBComQUeCYBBYp6qPYrvIkLiZKuHtsU',
    appId: '1:70223472961:web:b43880dfd229a3ecd419c0',
    messagingSenderId: '70223472961',
    projectId: 'fir-task-490d9',
    authDomain: 'fir-task-490d9.firebaseapp.com',
    storageBucket: 'fir-task-490d9.appspot.com',
    measurementId: 'G-5KHDMDFG5S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWcK2SXFtJsLMbsEXpuS5S6zFKu31vsS4',
    appId: '1:385809129495:ios:5c33280108e7998e45bc52',
    messagingSenderId: '385809129495',
    projectId: 'appquanly-57c64',
    storageBucket: 'appquanly-57c64.firebasestorage.app',
    iosBundleId: 'com.example.doan',
  );

}